### ISSUE TITLE
创建数据库：python rebuildDB.py出现错误

### ISSUE THREAD

**Issue by pun3ma** [tangrela/ojbk_jiexi#1]
错误提示：
[root@gfw ojbk_jiexi]# python rebuildDB.py
Traceback (most recent call last):
  File "rebuildDB.py", line 2, in <module>
    from app import db
  File "/root/ojbk_jiexi/app/__init__.py", line 33, in <module>
    from app import views
  File "/root/ojbk_jiexi/app/views.py", line 24, in <module>
    from captcha import *
  File "/root/ojbk_jiexi/app/captcha.py", line 3, in <module>
    from PIL import Image, ImageDraw, ImageFont
ImportError: No module named PIL

**Comment by tangrela** [comment]
pip install PIL

**Comment by tea1111980** [comment]
应该是这个才对：pip install Pillow
